name: Mini-EVM CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 pytest

    - name: Lint with flake8
      run: |
        flake8 src --count --max-line-length=88 --statistics

    - name: Run unit tests
      run: pytest -q

    - name: Run Demo
      run: |
        python src/demo_mini_evm.py

    - name: Upload Charts
      uses: actions/upload-artifact@v3
      with:
        name: charts
        path: charts/

    - name: Upload Outputs
      uses: actions/upload-artifact@v3
      with:
        name: outputs
        path: outputs/
